export const options = [
    { value: 1, label: 'Czy pobierał Pan jakieś oprogramowanie?', trigger: '3' },
    { value: 2, label: 'Czy ma Pan dostęp do plików na komputerze?', trigger: '5' },
    { value: 3, label: 'Czy może Pan się zalogować do komputera?', trigger: '7' },
    { value: 4, label: 'Czy komputera używają inni członkowie rodziny?', trigger: '9' },
    { value: 5, label: 'Czy ma Pan dostęp do Internetu?', trigger: '11' },
    { value: 6, label: 'Czy z komputera korzysta ktoś jeszcze?', trigger: '13' },
    { value: 7, label: 'Czy Pańska sieć jest zabezpieczona?', trigger: '15' },
    { value: 8, label: 'Czy komputer działa w taki sam sposób jak wcześniej?', trigger: '17' },
    { value: 9, label: 'Czy działo się już coś takiego w przeszłości?', tdrigger: '19' },
    { value: 10, label: 'Z jakiego systemu operacyjnego Pan korzysta?', trigger: '21' },
    { value: 11, label: 'Czy podłączał Pan jakieś urządzenia nieznanego pochodzenia?', trigger: '23' },
    { value: 12, label: 'Czy klikał Pan w jakieś załączniki w wiadomościach?', trigger: '25' },
    { value: 13, label: 'Czy odwiedzał Pan jakieś podejrzane strony?', trigger: '27' },
    { value: 14, label: 'Czy używa Pan antywirusa?', trigger: '29' },
    { value: 15, label: 'Czy udostępniał Pan komuś swoje dane wrażliwe jak np. pesel?', trigger: '31' },
    { value: 16, label: 'Czy używa Pan swoich danych uwierzytelniających na cudzych komputerach?', trigger: '33' },
    { value: 17, label: 'Czy zgłosił Pan to na Policję?', trigger: '35' },
    { value: 18, label: 'Czy zgłosił Pan to do banku?', trigger: '37' },
    { value: 19, label: 'Czy zgłosił Pan to do operatora/adminstratora sieci?', trigger: '39' },
    { value: 20, label: 'Używa Pan laptopa czy komputera stacjonarnego?', trigger: '41' },
    { value: 21, label: 'Czy komputer jest Pana własnością?', trigger: '43' },
    { value: 22, label: 'Czy ktoś niepowołany ma dostęp do Pana danych osobowych?', trigger: '45' },
    { value: 23, label: 'Czy zauważył Pan jakieś podejrzane zachowanie komputera?', trigger: '47' },
    { value: 24, label: 'Czy korzysta Pan z uwierzytelniania wielopoziomowego?', trigger: '49' },
    { value: 25, label: 'Czy utracił Pan dostęp do konta pocztowego?', trigger: '51' },
    { value: 26, label: 'Czy używa Pan różnych haseł dostępu na różne platformy?', trigger: '53' },
    { value: 27, label: 'Czy ma Pan ustawione procedury odzyskiwania hasła?', trigger: '55' },
    { value: 28, label: 'Czy posiada i używa Pan klucza U2F (Universal 2nd Factor)?', trigger: '57' },
    { value: 29, label: 'Czy korzysta Pan z Internetu dostępnego publicznie?', trigger: '59' },
    { value: 30, label: 'Czy udział Pan komuś dostępu do komputera?', trigger: '61' },
    { value: 31, label: 'Czy podłączał Pan jakieś urządzenia, np. pendrive?', trigger: '63' },
    { value: 32, label: 'Czy z sieci korzystają inni użytkownicy?', trigger: '65' },
    { value: 33, label: 'Czy zwraca Pan uwagę na znaczek zamkniętej kłódki przy adresach URL?', trigger: '67' },
    { value: 34, label: 'Czy doświadczył Pan podobnego problemu w przeszłości?', trigger: '69' },
    { value: 35, label: 'Czy zwraca Pan uwagę na adres URL podczas logowania?', trigger: '71' },
    { value: 36, label: 'Czy ma Pan w domu więcej komputerów?', trigger: '73' },
    { value: 37, label: 'Czy używa Pan komputera do pracy?', trigger: '75' },
    { value: 38, label: 'Czy loguje się Pan do serwisów/banków na cudzych komputerach?', trigger: '77' },
    { value: 39, label: 'Czy problem dotyczy więcej niż jednego komputera?', trigger: '79' },
    { value: 40, label: 'Wiem z jakim problemem się Pan zmaga!', trigger: '82' },
]